# Generated by Django 5.1.1 on 2025-05-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_userprofile_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
