# Generated by Django 5.1.1 on 2025-05-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_alter_negotiation_options_negotiation_lender_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acc_num',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_ver',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
