# Generated by Django 5.1.1 on 2025-04-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_userprofile_dependents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
