# Generated by Django 5.1.1 on 2025-05-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
