# Generated by Django 5.1.1 on 2025-05-02 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_lendingmldata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_amount', models.PositiveIntegerField()),
                ('proposed_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proposed_duration_months', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_negotiations', to=settings.AUTH_USER_MODEL)),
                ('original_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanoffer')),
            ],
        ),
    ]
