# Generated by Django 5.1.1 on 2025-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Lender', 'Lender'), ('Borrower', 'Borrower')], default='Borrower', max_length=10),
        ),
    ]
