# Generated by Django 5.1.1 on 2025-05-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
