# Generated by Django 5.1.1 on 2025-05-02 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_remove_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negotiation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='negotiation',
            name='lender_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_negotiations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lender_negotiations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='proposed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='proposed_duration_months',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Counter Offered')], default='pending', max_length=10),
        ),
    ]
